### ISSUE TITLE
 jwt must be provided

### ISSUE THREAD

**Issue by jaydeep0621** [jaydeep0621/Registration-API#1]
**at Object.module.exports [as verify] (D:\JavaScript\Registration-API\node_modules\jsonwebtoken\verify.js:53:17)**
    at auth (D:\JavaScript\Registration-API\src\middleware\auth.js:10:33)
    at Layer.handle [as handle_request] (D:\JavaScript\Registration-API\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\JavaScript\Registration-API\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\JavaScript\Registration-API\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\JavaScript\Registration-API\node_modules\express\lib\router\layer.js:95:5)
    at D:\JavaScript\Registration-API\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\JavaScript\Registration-API\node_modules\express\lib\router\index.js:335:12)
    at next (D:\JavaScript\Registration-API\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (D:\JavaScript\Registration-API\node_modules\body-parser\lib\types\json.js:101:7)
    at Layer.handle [as handle_request] (D:\JavaScript\Registration-API\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\JavaScript\Registration-API\node_modules\express\lib\router\index.js:317:13)
    at D:\JavaScript\Registration-API\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\JavaScript\Registration-API\node_modules\express\lib\router\index.js:335:12)
    at next (D:\JavaScript\Registration-API\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\JavaScript\Registration-API\node_modules\express\lib\router\index.js:174:3)

cmd output 
![CMD](https://user-images.githubusercontent.com/64656906/94440797-a85d4c00-01bf-11eb-9344-5cfb3c497603.png)

postman Ouput
![POSTMAN](https://user-images.githubusercontent.com/64656906/94440830-b0b58700-01bf-11eb-94b4-9fc51c0d1635.png)

**Comment by jaydeep0621** [comment]
This Issue was resolved because we will not use JWT in Login API.
