### ISSUE TITLE
Error While Connecting with Express-session in Database Model->Session.js

### ISSUE THREAD

**Issue by jaydeep0621** [jaydeep0621/Registration-API#2]
throw new TypeError('Invalid value for schema path `' + fullPath +
      ^

TypeError: Invalid value for schema path `type`, got value "undefined"
    at Schema.add (D:\JavaScript\Registration-API\node_modules\mongoose\lib\schema.js:473:13)
    at new Schema (D:\JavaScript\Registration-API\node_modules\mongoose\lib\schema.js:127:10)
    at Schema.interpretAsType (D:\JavaScript\Registration-API\node_modules\mongoose\lib\schema.js:960:29)
    at Schema.path (D:\JavaScript\Registration-API\node_modules\mongoose\lib\schema.js:686:27)
    at Schema.add (D:\JavaScript\Registration-API\node_modules\mongoose\lib\schema.js:496:12)
    at new Schema (D:\JavaScript\Registration-API\node_modules\mongoose\lib\schema.js:127:10)
    at Object.<anonymous> (D:\JavaScript\Registration-API\src\model\session.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\JavaScript\Registration-API\src\controller\control.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

![image](https://user-images.githubusercontent.com/64656906/101261734-63c1d400-375f-11eb-823f-31918dfa90aa.png)

Session.js File Image

![image](https://user-images.githubusercontent.com/64656906/101261742-763c0d80-375f-11eb-9388-affe42dd39d4.png)

**Comment by jaydeep0621** [comment]
Express-Session, Model --> Session.js to authenticate the User. JavaScript is Case Sensitive so it stores ObjectId as **ObjectID** which returns NULL Value to the user.

![image](https://user-images.githubusercontent.com/64656906/101672914-764c4e00-3a7c-11eb-9753-ed7435dba594.png)
